# Generated by Django 4.2.23 on 2025-08-01 00:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_user_role_group_user_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='AwardReason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('coins', models.PositiveIntegerField()),
                ('cooldown_days', models.PositiveIntegerField(default=0)),
                ('is_special', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='CoinAward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('comment', models.TextField(blank=True)),
                ('reason', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.awardreason')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_awards', to=settings.AUTH_USER_MODEL)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='given_awards', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
