# Generated by Django 4.2.23 on 2025-08-01 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_productcategory_alter_product_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата рождения'),
        ),
        migrations.AddField(
            model_name='user',
            name='parent_full_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='ФИО родителя'),
        ),
        migrations.AddField(
            model_name='user',
            name='parent_phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Телефон родителя'),
        ),
    ]
