# Generated by Django 4.2.23 on 2025-08-02 03:28

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_user_birth_date_user_parent_full_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/', validators=[core.validators.validate_file_type, core.validators.validate_file_size]),
        ),
    ]
