# Generated by Django 4.2.23 on 2025-08-06 12:51

from django.db import migrations


def create_award_templates(apps, schema_editor):
    AwardReason = apps.get_model('core', 'AwardReason')
    
    templates = [
        ("За работу на уроке", 10, 0, False),
        ("Не пропускать занятия месяц", 30, 30, False),
        ("Придумай название своей команды", 30, 0, True),
        ("Нарисуй логотип своей команды", 40, 0, True),
        ("Стань помощником педагога на занятии", 30, 0, False),
        ("Создай собственный проект (не по программе курса не чаще 1 раза в месяц)", 40, 30, True),
        ("Создай групповой проект (не по программе курса не чаще 1 раза в месяц)", 50, 30, True),
        ("Выполняй задания дома", 30, 0, False),
        ("Участие в соревнованиях", 70, 0, True),
        ("Отзыв родителей (положительный)", 40, 0, False),
        ("Отзыв родителей (отличный)", 80, 0, True),
    ]
    
    for name, coins, cooldown, is_special in templates:
        AwardReason.objects.get_or_create(
            name=name,
            defaults={
                'coins': coins,
                'cooldown_days': cooldown,
                'is_special': is_special
            }
        )


def reverse_create_award_templates(apps, schema_editor):
    # Можно оставить пустым, так как удаление шаблонов может быть нежелательным
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_product_price_alter_profile_astrocoins_and_more'),
    ]

    operations = [
        migrations.RunPython(create_award_templates, reverse_create_award_templates),
    ]
