# Generated by Django 4.2.23 on 2025-08-07 00:43

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20250806_2251'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='ФИО родителя')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('address', models.TextField(blank=True, verbose_name='Адрес')),
                ('work_place', models.CharField(blank=True, max_length=255, verbose_name='Место работы')),
                ('notes', models.TextField(blank=True, verbose_name='Дополнительные заметки')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Родитель',
                'verbose_name_plural': 'Родители',
                'ordering': ['full_name'],
            },
        ),
        migrations.AlterField(
            model_name='user',
            name='parent_full_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='ФИО родителя (устаревшее)'),
        ),
        migrations.AlterField(
            model_name='user',
            name='parent_phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Телефон родителя (устаревшее)'),
        ),
        migrations.AddField(
            model_name='user',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='core.parent', verbose_name='Родитель'),
        ),
    ]
