# Generated by Django 4.2.23 on 2025-08-22 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_product_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchase',
            options={'ordering': ['-created_at'], 'verbose_name': 'Покупка', 'verbose_name_plural': 'Покупки'},
        ),
        migrations.AddField(
            model_name='purchase',
            name='delivered',
            field=models.BooleanField(default=False, verbose_name='Товар выдан'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='delivered_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата выдачи'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Примечания к выдаче'),
        ),
    ]
