# Generated by Django 4.2.23 on 2025-08-22 11:06

import core.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_purchase_options_purchase_delivered_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', core.models.CaseInsensitiveUserManager()),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='available_cities',
            field=models.ManyToManyField(blank=True, help_text='Выберите города где доступен этот товар', related_name='products', to='core.city', verbose_name='Доступен в городах'),
        ),
        migrations.AddField(
            model_name='user',
            name='cities',
            field=models.ManyToManyField(blank=True, help_text='Города где работает учитель', related_name='teachers', to='core.city', verbose_name='Города'),
        ),
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.ForeignKey(blank=True, help_text='Основной город (для администраторов и учеников)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.city', verbose_name='Город'),
        ),
    ]
