# Generated by Django 4.2.23 on 2025-08-22 13:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_add_regional_system'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='available_cities',
        ),
        migrations.AddField(
            model_name='product',
            name='city',
            field=models.ForeignKey(blank=True, help_text='Город в котором создан этот товар', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='core.city', verbose_name='Город'),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='city',
            field=models.ForeignKey(blank=True, help_text='Город в котором создана эта категория', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='core.city', verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='group',
            name='curator',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'city_admin'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='curated_groups', to=settings.AUTH_USER_MODEL, verbose_name='Куратор'),
        ),
        migrations.AlterField(
            model_name='group',
            name='teacher',
            field=models.ForeignKey(limit_choices_to={'role__in': ['teacher', 'city_admin']}, on_delete=django.db.models.deletion.CASCADE, related_name='teaching_groups', to=settings.AUTH_USER_MODEL, verbose_name='Преподаватель'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('student', 'Ученик'), ('teacher', 'Преподаватель'), ('city_admin', 'Администратор города')], default='student', max_length=10),
        ),
    ]
